Project: Restaurant Page
Samitti/RESTAURANT-PAGE pull request #1
Opened 2020-09-23 13:24 UTC by Samitti

I have completed the Project Restaurant Page, kindly review my code.

2020-09-23 15:12 UTC, Dandush03 requested changes
# Status: :red_circle: : Require Changes :red_circle: : 
### Great Work So Far :muscle: 
You must avoid at all costs disabling EsLint. (Most of the time is correct.)
Don't forget for this project ES6 Syntax is a must.
Check out my recommendation below, they apply for all places where the same error repeat, I will not point  out each time it happens 
# Happy Coding :nerd_face: :computer:

2020-09-23 15:12 UTC, Dandush03 commented on src/contact.js
> +};
- [ ] Since you're exporting only one page, use export default

2020-09-23 15:12 UTC, Dandush03 commented on src/menu.js
> +const menuPage = (function () {
### -[ ] use arrow function ES6 Syntax

2020-09-24 08:09 UTC, Samitti commented
I have made the changes rewquired by the previous review, but for some reason I couldn't understand the export default is not working for me so I have disabled the eslint error. kindly review my code .

2020-09-24 08:54 UTC, rOluochKe approved these changes
Hello @Samitti 
### Well done, you got it right :clap: The project has been approved. Congratulations :boom: :100:
### Merge and submit the project. Good luck with the next one.
- Happy coding!

2020-09-24 09:14 UTC, merged